test: &default

  # Credentials for REST APIs
  client_id: AUrT7Ic-5FOKNouqUyUO-nMUGtQkQcbi7wjje0xX9EDplPENaq86vn-g1Kw6BIlG5-_yVtsClxCkF8Rl
  client_secret: EEn1iyeTg77mintpN3wbLaKA3Y_ltC1j7IQXI6-9TegB7obOFuzFBLx64cbtidCh9GRfy3A8GL3j4gc5

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: marxelofacilito@facilito.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
