# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90e6c589c1db19f11c6be916a166f42cc80378e74ca77d2145e7a3947e6cd8ae4467ed8bd7cd249f97333ba74f6bf6372a1de20e2a1fb0416dfebb6e47b3b54a

test:
  secret_key_base: d47f5764bf2a0c4c4df45de6b34e4bb06055635a4d10aaa39a285d99dd78930735ce9d024a6f5077f126fe0f382b1352206743caefef8fc53e2c57dc6f60fcf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
